#if !canImport(ObjectiveC)
import XCTest

extension LZSSTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LZSSTests = [
        ("testCompressGreenEggsAndHam", testCompressGreenEggsAndHam),
        ("testDecodePerformance", testDecodePerformance),
        ("testDecompressGreenEggsAndHam", testDecompressGreenEggsAndHam),
        ("testEncodePerformance", testEncodePerformance),
        ("testLargeStream", testLargeStream),
        ("testPartialDecoding", testPartialDecoding),
        ("testPartialEncoding", testPartialEncoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LZSSTests.__allTests__LZSSTests),
    ]
}
#endif
