language: minimal
dist: xenial

env:
  global:
    - REPO=stdswift/build
  matrix:
    - SWIFT=5.1 OS=trusty
    - SWIFT=5.1 OS=xenial
    - SWIFT=5.1 OS=bionic
    - SWIFT=5.2 OS=xenial
    - SWIFT=5.2 OS=bionic
    - SWIFT=5.2 OS=focal

matrix:
  include:
    - os: osx
      env:
      osx_image: xcode11.3
    - os: osx
      env:
      osx_image: xcode11.6
    - os: osx
      env:
      osx_image: xcode12

install:
  - |
    set -e
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      docker pull $REPO:$OS-$SWIFT
    fi

script:
  - |
    set -e
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      docker run --volume `pwd`:/code --workdir /code $REPO:$OS-$SWIFT swift test --enable-test-discovery
    fi
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      swift build -Xswiftc=-Xfrontend -Xswiftc=-disable-objc-interop
      swift test --enable-code-coverage
    fi

after_success:
  - |
    set -e
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      profile=.build/debug/codecov/default.profdata
      executable=.build/debug/${PWD##*/}PackageTests.xctest/Contents/MacOS/${PWD##*/}PackageTests
      coverage=.build/debug/codecov/${PWD##*/}.coverage.txt
      xcrun llvm-cov show -instr-profile $profile $executable > $coverage
      bash <(curl -s https://codecov.io/bash) -f $coverage
    fi
